import React, { useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ChevronRight, Flame, LogIn, LogOut, PlusCircle, ShieldCheck, Sparkles, UserPlus } from 'lucide-react-native';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api, auth } from '../api';
import { useAuth } from '../auth-context';
import { Button, Card, Input, Pill, ScreenTitle } from '../components';
import { colors, fonts } from '../theme';
const bunny=require('../../assets/bunny_reading.png');

export function LoginScreen({navigation}:any){const {setUser}=useAuth();const [identifier,setIdentifier]=useState('');const [password,setPassword]=useState('');const mutation=useMutation({mutationFn:()=>auth.login(identifier,password),onSuccess:u=>{setUser(u);navigation.goBack()},onError:(e:any)=>Alert.alert('Login failed',e.userMessage)});return <AuthShell title="Welcome back!" subtitle="Continue your gentle English learning journey."><Input placeholder="Username or email" autoCapitalize="none" value={identifier} onChangeText={setIdentifier}/><Input placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/><Button title={mutation.isPending?'Logging in...':'Log In'} variant="blue" disabled={!identifier||!password||mutation.isPending} onPress={()=>mutation.mutate()}/><Pressable onPress={()=>navigation.navigate('ForgotPassword')}><Text style={s.link}>Forgot password?</Text></Pressable><View style={s.switch}><Text style={s.muted}>New to AuraEnglish?</Text><Pressable onPress={()=>navigation.navigate('Register')}><Text style={s.link}> Create account</Text></Pressable></View></AuthShell>}
export function RegisterScreen({navigation}:any){const {setUser}=useAuth();const [username,setUsername]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const mutation=useMutation({mutationFn:()=>auth.register(username,email,password,confirm),onSuccess:u=>{setUser(u);navigation.popToTop()},onError:(e:any)=>Alert.alert('Registration failed',e.userMessage)});return <AuthShell title="Create your account" subtitle="Start learning one lovely word at a time."><Input placeholder="Username" autoCapitalize="none" value={username} onChangeText={setUsername}/><Input placeholder="Email" keyboardType="email-address" autoCapitalize="none" value={email} onChangeText={setEmail}/><Input placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/><Input placeholder="Confirm password" secureTextEntry value={confirm} onChangeText={setConfirm}/><Button title={mutation.isPending?'Creating...':'Sign Up'} disabled={!username||!email||!password||password!==confirm||mutation.isPending} onPress={()=>mutation.mutate()}/><View style={s.switch}><Text style={s.muted}>Already have an account?</Text><Pressable onPress={()=>navigation.goBack()}><Text style={s.link}> Log in</Text></Pressable></View></AuthShell>}
export function ForgotPasswordScreen({navigation}:any){const [identifier,setIdentifier]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const mutation=useMutation({mutationFn:()=>api.post('/auth/forgot-password',{identifier,newPassword:password,confirmPassword:confirm}),onSuccess:()=>{Alert.alert('Password updated','You can now log in with your new password.',[{text:'Log in',onPress:()=>navigation.navigate('Login')}])},onError:(e:any)=>Alert.alert('Could not reset password',e.userMessage)});return <AuthShell title="Reset password" subtitle="No worries — we'll get you back to learning."><Input placeholder="Email or username" value={identifier} onChangeText={setIdentifier}/><Input placeholder="New password" secureTextEntry value={password} onChangeText={setPassword}/><Input placeholder="Confirm new password" secureTextEntry value={confirm} onChangeText={setConfirm}/><Button title="Update Password" disabled={!identifier||!password||password!==confirm} onPress={()=>mutation.mutate()}/></AuthShell>}
function AuthShell({title,subtitle,children}:any){return <ScrollView contentContainerStyle={s.authPage} keyboardShouldPersistTaps="handled"><View style={s.logo}><Sparkles size={28} color={colors.white}/></View><Text style={s.brand}>Aura<Text style={{color:colors.pink}}>English</Text></Text><Card style={s.form}><Text style={s.authTitle}>{title}</Text><Text style={s.authSub}>{subtitle}</Text>{children}</Card></ScrollView>}

export function AccountScreen({navigation}:any){const {user,signOut}=useAuth();const qc=useQueryClient();const logout=async()=>{await signOut();qc.clear()};return <ScrollView contentContainerStyle={s.page}><ScreenTitle title="More" subtitle="Your profile, contribution tools, and account settings."/>{user?<><Card style={s.profile}><Image source={bunny} style={s.avatar}/><View style={{flex:1}}><Text style={s.name}>{user.displayName||user.username}</Text><Text style={s.email}>{user.email}</Text><Pill color={user.role==='admin'?colors.pinkDark:colors.green} background={user.role==='admin'?colors.pinkSoft:'#ECFDF5'}>{user.role==='admin'?'👑 Admin':user.role==='contributor'?'⭐ Contributor':'🌱 Student'}</Pill></View></Card><Menu icon={<PlusCircle color={colors.amber}/>} title="Contributions" text="Share vocabulary and readings" onPress={()=>navigation.navigate('Contribution')}/><Menu icon={<Flame color={colors.amber}/>} title="Learning streak" text="Keep your daily rhythm alive"/><Menu icon={<ShieldCheck color={colors.blue}/>} title="Account & privacy" text="Your learning data is yours"/><Button title="Log Out" variant="danger" icon={<LogOut size={17} color={colors.danger}/>} onPress={logout}/></>:<Card style={s.guest}><Image source={bunny} style={s.guestBunny}/><Text style={s.guestTitle}>Your learning home awaits</Text><Text style={s.authSub}>Log in to save words, build decks, track streaks, and contribute.</Text><Button title="Log In" variant="blue" icon={<LogIn size={17} color={colors.white}/>} onPress={()=>navigation.navigate('Login')}/><Button title="Create Account" variant="white" icon={<UserPlus size={17} color={colors.secondary}/>} onPress={()=>navigation.navigate('Register')}/></Card>}</ScrollView>}
function Menu({icon,title,text,onPress}:any){return <Pressable onPress={onPress}><Card style={s.menu}>{icon}<View style={{flex:1}}><Text style={s.menuTitle}>{title}</Text><Text style={s.menuText}>{text}</Text></View><ChevronRight size={19} color={colors.muted}/></Card></Pressable>}

export function ContributionScreen(){const [type,setType]=useState<'vocabulary'|'reading'>('vocabulary');const [title,setTitle]=useState('');const [meaning,setMeaning]=useState('');const [content,setContent]=useState('');const mutation=useMutation({mutationFn:()=>api.post('/contributions',type==='vocabulary'?{type,payload:{text:title,meaningVi:meaning,exampleEn:content}}:{type,payload:{title,subtitle:meaning,content}}),onSuccess:()=>{Alert.alert('Thank you!','Your contribution was submitted for review.');setTitle('');setMeaning('');setContent('')},onError:(e:any)=>Alert.alert('Submission failed',e.userMessage)});return <ScrollView contentContainerStyle={s.page}><ScreenTitle title="Contributions" subtitle="Help the AuraEnglish library grow with useful, human-friendly content."/><Card><View style={s.typeRow}><Button title="Vocabulary" variant={type==='vocabulary'?'pink':'white'} onPress={()=>setType('vocabulary')}/><Button title="Reading" variant={type==='reading'?'pink':'white'} onPress={()=>setType('reading')}/></View><Text style={s.field}>{type==='vocabulary'?'WORD OR PHRASE':'ARTICLE TITLE'}</Text><Input placeholder={type==='vocabulary'?'e.g. break a leg':'e.g. The Science of Memory'} value={title} onChangeText={setTitle}/><Text style={s.field}>{type==='vocabulary'?'VIETNAMESE MEANING':'SHORT DESCRIPTION'}</Text><Input placeholder="Write a clear explanation..." value={meaning} onChangeText={setMeaning}/><Text style={s.field}>{type==='vocabulary'?'ENGLISH EXAMPLE':'ARTICLE CONTENT'}</Text><Input placeholder="Write the full content here..." multiline value={content} onChangeText={setContent} style={{minHeight:130,textAlignVertical:'top'}}/><Button title={mutation.isPending?'Submitting...':'Submit Contribution'} disabled={!title||!meaning||mutation.isPending} onPress={()=>mutation.mutate()}/></Card></ScrollView>}
const s=StyleSheet.create({authPage:{flexGrow:1,padding:22,paddingTop:60,backgroundColor:colors.background,alignItems:'center'},logo:{width:58,height:58,borderRadius:20,backgroundColor:colors.pink,alignItems:'center',justifyContent:'center'},brand:{fontFamily:fonts.bold,fontSize:23,color:colors.ink,marginVertical:10},form:{width:'100%',gap:13,marginTop:15},authTitle:{fontFamily:fonts.bold,fontSize:27,color:colors.ink,textAlign:'center'},authSub:{fontFamily:fonts.medium,fontSize:13,color:colors.secondary,lineHeight:19,textAlign:'center',marginBottom:7},link:{fontFamily:fonts.bold,fontSize:12,color:colors.blue,textAlign:'center'},switch:{flexDirection:'row',justifyContent:'center'},muted:{fontFamily:fonts.medium,fontSize:12,color:colors.secondary},page:{padding:18,paddingBottom:110,gap:13},profile:{flexDirection:'row',alignItems:'center',gap:15},avatar:{width:70,height:70,borderRadius:35,backgroundColor:colors.pinkSoft},name:{fontFamily:fonts.bold,fontSize:20,color:colors.ink},email:{fontFamily:fonts.medium,fontSize:11,color:colors.secondary,marginVertical:4},menu:{flexDirection:'row',alignItems:'center',gap:14,padding:17},menuTitle:{fontFamily:fonts.bold,fontSize:14,color:colors.ink},menuText:{fontFamily:fonts.medium,fontSize:10,color:colors.secondary,marginTop:2},guest:{alignItems:'center',gap:12,paddingVertical:28},guestBunny:{width:130,height:130,resizeMode:'contain'},guestTitle:{fontFamily:fonts.bold,fontSize:21,color:colors.ink},typeRow:{flexDirection:'row',gap:8,marginBottom:12},field:{fontFamily:fonts.bold,fontSize:9,color:colors.secondary,letterSpacing:1,marginTop:12,marginBottom:6}});
