import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, Bookmark, CheckCircle2, ChevronRight, Volume2 } from 'lucide-react-native';
import * as Speech from 'expo-speech';
import { api, unwrap } from '../api';
import { Button, Card, Empty, Loading, Pill, ScreenTitle, SearchBox } from '../components';
import { colors, fonts } from '../theme';
import { useAuth } from '../auth-context';

const types=[['','All'],['single_word','Words'],['collocation','Collocations'],['phrasal_verb','Phrasal verbs'],['idiom','Idioms']];
const levels=['','A1','A2','B1','B2','C1','C2'];

export function DictionaryScreen({ navigation }:any){
 const [search,setSearch]=useState(''); const [type,setType]=useState(''); const [level,setLevel]=useState('');const [topicId,setTopicId]=useState('');const [page,setPage]=useState(1);
 const {data:topics}=useQuery({queryKey:['topics'],queryFn:async()=>unwrap<any[]>(await api.get('/topics'))});
 const {data,isLoading}=useQuery({queryKey:['vocabularies',search,type,level,topicId,page],queryFn:async()=>unwrap<any>(await api.get('/vocabularies',{params:{search:search||undefined,type:type||undefined,level:level||undefined,topicId:topicId||undefined,page,limit:12}}))});
 const items=data?.items||data||[];
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><ScreenTitle title="Dictionary" subtitle="Explore words, phrases, and expressions for every level."/><SearchBox placeholder="Search vocabulary..." value={search} onChangeText={v=>{setSearch(v);setPage(1)}}/><Text style={s.filterLabel}>VOCABULARY TYPE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{types.map(([v,l])=><Chip key={v} text={l} active={type===v} color={colors.pink} onPress={()=>{setType(v);setPage(1)}}/>)}</ScrollView><Text style={s.filterLabel}>CEFR LEVEL</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{levels.map(v=><Chip key={v} text={v||'All Levels'} active={level===v} color={colors.blue} onPress={()=>{setLevel(v);setPage(1)}}/>)}</ScrollView>{topics?.length?<><Text style={s.filterLabel}>TOPIC</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Chip text="All Topics" active={!topicId} color={colors.green} onPress={()=>{setTopicId('');setPage(1)}}/>{topics.map((t:any)=><Chip key={t.id} text={t.name} active={topicId===t.id} color={colors.green} onPress={()=>{setTopicId(t.id);setPage(1)}}/>)}</ScrollView></>:null}<View style={s.resultHead}><Text style={s.resultTitle}>{data?.total??items.length} results</Text><Text style={s.muted}>Page {data?.page||page} / {data?.totalPages||1}</Text></View>{isLoading?<Loading label="Searching dictionary..."/>:items.length?items.map((v:any)=><VocabCard key={v.id||v._id} v={v} onPress={()=>navigation.navigate('VocabularyDetail',{id:v.id||v._id})} onLogin={()=>navigation.navigate('Login')}/>):<Empty title="No matching words" text="Try changing your search or filters."/>}{(data?.totalPages||1)>1?<View style={s.pagination}><Button title="‹ Previous" variant="white" disabled={page<=1} onPress={()=>setPage(p=>p-1)}/><Button title="Next ›" variant="blue" disabled={page>=data.totalPages} onPress={()=>setPage(p=>p+1)}/></View>:null}</ScrollView>
}
function Chip({text,active,color,onPress}:any){return <Pressable onPress={onPress} style={[s.chip,{backgroundColor:active?color:'#F1F5F9'}]}><Text style={[s.chipText,{color:active?colors.white:colors.secondary}]}>{text}</Text></Pressable>}
function VocabCard({v,onPress,onLogin}:any){const {user}=useAuth();const qc=useQueryClient();const save=useMutation({mutationFn:()=>api.post(`/vocabularies/${v.id||v._id}/save`),onSuccess:()=>qc.invalidateQueries({queryKey:['vocabularies']}),onError:(e:any)=>Alert.alert('Cannot save',e.userMessage)});return <Pressable onPress={onPress}><Card style={{marginBottom:12}}><View style={s.between}><Pill color={v.type==='idiom'?colors.pinkDark:colors.blue} background={v.type==='idiom'?colors.pinkSoft:colors.blueSoft}>{(v.type||'word').replace('_',' ')}</Pill>{v.level?<Pill color={colors.green} background="#ECFDF5">{v.level}</Pill>:null}</View><Text style={s.word}>{v.text}</Text>{v.phonetic?<Text style={s.phonetic}>{v.phonetic}</Text>:null}<Text style={s.meaning}>{v.meanings?.[0]?.meaningVi||v.meaningVi||'Chưa có nghĩa'}</Text>{v.meanings?.[0]?.meaningEn?<Text style={s.meaningEn}>{v.meanings[0].meaningEn}</Text>:null}<View style={s.cardFoot}><Pressable onPress={e=>{e.stopPropagation();user?save.mutate():onLogin()}} style={s.save}><Bookmark size={17} color={v.userStatus==='saved'?colors.pink:colors.muted} fill={v.userStatus==='saved'?colors.pink:'transparent'}/><Text style={s.saveText}>SAVE</Text></Pressable><View style={s.detail}><Text style={s.detailText}>DETAILS</Text><ChevronRight size={16} color={colors.blue}/></View></View></Card></Pressable>}

export function VocabularyDetailScreen({route,navigation}:any){
 const {id}=route.params; const {user}=useAuth(); const qc=useQueryClient();
 const {data,isLoading}=useQuery({queryKey:['vocabulary',id],queryFn:async()=>unwrap<any>(await api.get(`/vocabularies/${id}`))});
 const action=useMutation({mutationFn:async(path:string)=>api.post(`/vocabularies/${id}/${path}`),onSuccess:()=>{qc.invalidateQueries({queryKey:['vocabulary',id]});qc.invalidateQueries({queryKey:['vocabularies']})},onError:(e:any)=>Alert.alert('Oops',e.userMessage)});
 if(isLoading)return <Loading/>; if(!data)return <Empty title="Word not found"/>; const v=data.vocabulary||data; const status=data.userProgress?.status||'new';
 return <ScrollView contentContainerStyle={s.page}><Pressable style={s.back} onPress={()=>navigation.goBack()}><ArrowLeft size={18} color={colors.secondary}/><Text style={s.backText}>Back to Dictionary</Text></Pressable><Card><View style={s.between}><View style={{flexDirection:'row',gap:7}}><Pill color={colors.blue} background={colors.blueSoft}>{(v.type||'word').replace('_',' ')}</Pill>{v.level?<Pill>{v.level}</Pill>:null}</View>{status!=='new'?<Pill color={colors.secondary} background="#F1F5F9">{status}</Pill>:null}</View><View style={s.audioRow}><View><Text style={s.detailWord}>{v.text}</Text>{v.phonetic?<Text style={s.detailPhonetic}>{v.phonetic}</Text>:null}</View><Pressable style={s.audio} onPress={()=>v.audioUrl?null:Speech.speak(v.text,{language:'en-US'})}><Volume2 size={23} color={colors.blue}/></Pressable></View>{user?<View style={s.actions}><Button title={status==='saved'?'Saved':'Save'} variant={status==='saved'?'soft':'white'} icon={<Bookmark size={16} color={colors.pinkDark}/>} onPress={()=>action.mutate('save')}/><Button title="Known" variant="white" icon={<CheckCircle2 size={16} color={colors.blue}/>} onPress={()=>action.mutate('mark-known')}/><Button title="Difficult" variant="white" icon={<AlertTriangle size={16} color={colors.amber}/>} onPress={()=>action.mutate('mark-difficult')}/></View>:null}<View style={s.divider}/><Text style={s.section}>Meanings</Text>{v.meanings?.map((m:any,i:number)=><View style={s.meaningBox} key={i}><Text style={s.meaningDetail}>{i+1}. {m.meaningVi}</Text>{m.meaningEn?<Text style={s.meaningEn}>{m.meaningEn}</Text>:null}{m.note?<Text style={s.note}>Note: {m.note}</Text>:null}{m.examples?.map((ex:any,j:number)=><View style={s.example} key={j}><Text style={s.exampleEn}>{ex.exampleEn}</Text>{ex.exampleVi?<Text style={s.meaningEn}>{ex.exampleVi}</Text>:null}</View>)}</View>)}</Card></ScrollView>
}
const s=StyleSheet.create({page:{padding:18,paddingBottom:110},chips:{gap:8,paddingBottom:3},chip:{paddingHorizontal:15,paddingVertical:9,borderRadius:999},chipText:{fontFamily:fonts.bold,fontSize:12},filterLabel:{fontFamily:fonts.bold,fontSize:10,letterSpacing:1,color:colors.secondary,marginTop:17,marginBottom:9},resultHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginVertical:20},resultTitle:{fontFamily:fonts.bold,fontSize:18,color:colors.ink},muted:{fontFamily:fonts.medium,fontSize:10,color:colors.muted},pagination:{flexDirection:'row',justifyContent:'space-between',gap:10,marginTop:12},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},word:{fontFamily:fonts.bold,fontSize:23,color:colors.ink,marginTop:16},phonetic:{fontFamily:fonts.medium,fontSize:11,color:colors.muted,marginTop:2},meaning:{fontFamily:fonts.bold,fontSize:15,color:colors.ink,marginTop:12,lineHeight:21},meaningEn:{fontFamily:fonts.medium,fontSize:12,color:colors.secondary,fontStyle:'italic',lineHeight:18,marginTop:3},cardFoot:{borderTopWidth:1,borderTopColor:'#F1F5F9',marginTop:17,paddingTop:13,flexDirection:'row',justifyContent:'space-between'},save:{flexDirection:'row',gap:6,alignItems:'center'},saveText:{fontFamily:fonts.bold,fontSize:9,color:colors.secondary,letterSpacing:.8},detail:{flexDirection:'row',alignItems:'center'},detailText:{fontFamily:fonts.bold,fontSize:9,color:colors.blue,letterSpacing:.8},back:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:16},backText:{fontFamily:fonts.bold,fontSize:13,color:colors.secondary},audioRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginVertical:22},detailWord:{fontFamily:fonts.bold,fontSize:38,color:colors.ink,letterSpacing:-1},detailPhonetic:{fontFamily:fonts.medium,color:colors.secondary,fontSize:16},audio:{width:45,height:45,borderRadius:23,backgroundColor:colors.blueSoft,alignItems:'center',justifyContent:'center'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8},divider:{height:1,backgroundColor:'#F1F5F9',marginVertical:24},section:{fontFamily:fonts.bold,fontSize:20,color:colors.ink,marginBottom:14},meaningBox:{padding:16,borderRadius:18,backgroundColor:'#F8FAFC',borderWidth:1,borderColor:'#F1F5F9',marginBottom:12},meaningDetail:{fontFamily:fonts.bold,fontSize:16,color:colors.ink,lineHeight:22},note:{fontFamily:fonts.semibold,fontSize:10,color:colors.pinkDark,marginTop:7},example:{backgroundColor:colors.white,borderRadius:13,padding:12,marginTop:10},exampleEn:{fontFamily:fonts.semibold,fontSize:13,color:colors.ink,lineHeight:19}});
