import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, Bookmark, CheckCircle2, Layers, Search, Sparkles, Volume2 } from 'lucide-react-native';
import * as Speech from 'expo-speech';
import { api, unwrap } from '../api';
import { useAuth } from '../auth-context';
import { Button, Card, Empty, Loading, Pill, SearchBox } from '../components';
import { colors, fonts } from '../theme';

export function LookupScreen({navigation}:any){
 const {user}=useAuth();const qc=useQueryClient();const [query,setQuery]=useState('');const [submitted,setSubmitted]=useState('');const [result,setResult]=useState<any>(null);const [similar,setSimilar]=useState<any[]>([]);const [loading,setLoading]=useState(false);const [deckId,setDeckId]=useState('');
 const {data:decks}=useQuery({queryKey:['decks'],queryFn:async()=>unwrap<any>(await api.get('/flashcard-decks')),enabled:!!user});
 const runSearch=async()=>{const word=query.trim();if(!word)return;setSubmitted(word);setLoading(true);setResult(null);setSimilar([]);try{const data=unwrap<any>(await api.get('/vocabularies',{params:{search:word,limit:10}}));const items=data?.items||[];const exact=items.find((x:any)=>x.text?.trim().toLowerCase()===word.toLowerCase());if(exact)setResult(exact);else setSimilar(items)}catch(e:any){Alert.alert('Search failed',e.userMessage)}finally{setLoading(false)}};
 const ai=useMutation({mutationFn:async()=>unwrap<any>(await api.post('/vocabularies/ai-define',{text:submitted})),onSuccess:setResult,onError:(e:any)=>Alert.alert('AI definition failed',e.userMessage)});
 const vocabAction=useMutation({mutationFn:async(path:string)=>api.post(`/vocabularies/${result.id||result._id}/${path}`),onSuccess:()=>qc.invalidateQueries({queryKey:['vocabularies']}),onError:(e:any)=>Alert.alert('Action failed',e.userMessage)});
 const add=useMutation({mutationFn:async()=>api.post(`/flashcard-decks/${deckId}/cards`,{vocabularyId:result.id||result._id}),onSuccess:()=>{Alert.alert('Added','Vocabulary added to your deck.');qc.invalidateQueries({queryKey:['decks']})},onError:(e:any)=>Alert.alert('Cannot add card',e.userMessage)});
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Pressable style={s.back} onPress={()=>navigation.goBack()}><ArrowLeft size={18} color={colors.secondary}/><Text style={s.backText}>Back</Text></Pressable><View style={s.titleRow}><View style={s.searchIcon}><Search size={22} color={colors.white}/></View><View><Text style={s.title}>Vocabulary Lookup</Text><Text style={s.subtitle}>Search any word or phrase</Text></View></View><View style={s.searchRow}><View style={{flex:1}}><SearchBox autoFocus placeholder="e.g. curious, vertical farming..." value={query} onChangeText={setQuery} onSubmitEditing={runSearch} returnKeyType="search"/></View><Button title="Search" variant="blue" onPress={runSearch}/></View>{loading?<Loading label="Searching dictionary database..."/>:result?<ResultCard v={result} user={user} decks={decks?.myDecks||[]} deckId={deckId} setDeckId={setDeckId} onAction={(x:string)=>vocabAction.mutate(x)} onAdd={()=>add.mutate()} onOpen={()=>navigation.navigate('VocabularyDetail',{id:result.id||result._id})}/>:submitted?<>{similar.length?<><Text style={s.section}>Similar results</Text>{similar.map(v=><Pressable key={v.id||v._id} onPress={()=>setResult(v)}><Card style={{marginBottom:10}}><Text style={s.wordSmall}>{v.text}</Text><Text style={s.meaning}>{v.meanings?.[0]?.meaningVi}</Text></Card></Pressable>)}</>:<Empty title={`“${submitted}” isn't in the dictionary`} text="Let AI draft a definition for you."/>}<Button title={ai.isPending?'AI is defining...':'Define with AI'} icon={<Sparkles size={17} color={colors.white}/>} disabled={ai.isPending} onPress={()=>ai.mutate()}/></>:<Card style={s.welcome}><Text style={s.emoji}>🔎</Text><Text style={s.welcomeTitle}>What would you like to learn?</Text><Text style={s.subtitle}>Type a word above. Exact matches show meanings, examples, learning actions, and deck tools.</Text></Card>}</ScrollView>
}
function ResultCard({v,user,decks,deckId,setDeckId,onAction,onAdd,onOpen}:any){const m=v.meanings?.[0]||{};return <Card><View style={s.between}><View><Text style={s.word}>{v.text}</Text><Text style={s.phonetic}>{v.phonetic}</Text></View><Pressable style={s.audio} onPress={()=>Speech.speak(v.text,{language:'en-US'})}><Volume2 size={22} color={colors.blue}/></Pressable></View><View style={s.tags}><Pill color={colors.blue} background={colors.blueSoft}>{(v.type||'word').replace('_',' ')}</Pill>{v.level?<Pill>{v.level}</Pill>:null}{v.partOfSpeech?<Pill color={colors.secondary} background="#F1F5F9">{v.partOfSpeech}</Pill>:null}</View><View style={s.divider}/><Text style={s.meaningBig}>{m.meaningVi||v.meaningVi||'Chưa có nghĩa'}</Text>{m.meaningEn||v.meaningEn?<Text style={s.meaningEn}>{m.meaningEn||v.meaningEn}</Text>:null}{m.examples?.[0]||v.exampleEn?<View style={s.example}><Text style={s.exampleEn}>“{m.examples?.[0]?.exampleEn||v.exampleEn}”</Text><Text style={s.meaningEn}>{m.examples?.[0]?.exampleVi||v.exampleVi}</Text></View>:null}{user?<><View style={s.actions}><Button title="Save" variant="soft" icon={<Bookmark size={16} color={colors.pinkDark}/>} onPress={()=>onAction('save')}/><Button title="Known" variant="white" icon={<CheckCircle2 size={16} color={colors.blue}/>} onPress={()=>onAction('mark-known')}/><Button title="Difficult" variant="white" icon={<AlertTriangle size={16} color={colors.amber}/>} onPress={()=>onAction('mark-difficult')}/></View>{decks.length?<><Text style={s.deckLabel}>ADD TO FLASHCARD DECK</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}>{decks.map((d:any)=><Pressable key={d.id||d._id} onPress={()=>setDeckId(d.id||d._id)} style={[s.deck,deckId===(d.id||d._id)&&s.deckOn]}><Layers size={14} color={deckId===(d.id||d._id)?colors.white:colors.secondary}/><Text style={[s.deckText,deckId===(d.id||d._id)&&{color:colors.white}]}>{d.name}</Text></Pressable>)}</ScrollView><Button title="Add to selected deck" variant="blue" disabled={!deckId} onPress={onAdd}/></>:null}</>:null}<Button title="View full dictionary entry" variant="white" onPress={onOpen}/></Card>}
const s=StyleSheet.create({page:{padding:18,paddingBottom:70},back:{flexDirection:'row',alignItems:'center',gap:6,marginBottom:18},backText:{fontFamily:fonts.bold,fontSize:13,color:colors.secondary},titleRow:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:18},searchIcon:{width:46,height:46,borderRadius:17,backgroundColor:colors.pink,alignItems:'center',justifyContent:'center'},title:{fontFamily:fonts.bold,fontSize:24,color:colors.ink},subtitle:{fontFamily:fonts.medium,fontSize:12,color:colors.secondary,lineHeight:18},searchRow:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:18},welcome:{alignItems:'center',paddingVertical:40},emoji:{fontSize:42},welcomeTitle:{fontFamily:fonts.bold,fontSize:19,color:colors.ink,marginVertical:8},section:{fontFamily:fonts.bold,fontSize:18,color:colors.ink,marginVertical:13},wordSmall:{fontFamily:fonts.bold,fontSize:18,color:colors.pinkDark},meaning:{fontFamily:fonts.medium,fontSize:12,color:colors.secondary,marginTop:4},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},word:{fontFamily:fonts.bold,fontSize:34,color:colors.pinkDark},phonetic:{fontFamily:fonts.medium,fontSize:13,color:colors.muted,marginTop:3},audio:{width:44,height:44,borderRadius:22,backgroundColor:colors.blueSoft,alignItems:'center',justifyContent:'center'},tags:{flexDirection:'row',gap:7,flexWrap:'wrap',marginTop:15},divider:{height:1,backgroundColor:'#EEF2F6',marginVertical:18},meaningBig:{fontFamily:fonts.bold,fontSize:18,color:colors.ink,lineHeight:25},meaningEn:{fontFamily:fonts.medium,fontSize:12,color:colors.secondary,fontStyle:'italic',lineHeight:18,marginTop:4},example:{backgroundColor:'#F8FAFC',borderRadius:15,padding:13,marginTop:14},exampleEn:{fontFamily:fonts.semibold,fontSize:13,color:colors.ink,lineHeight:19},actions:{flexDirection:'row',flexWrap:'wrap',gap:7,marginVertical:17},deckLabel:{fontFamily:fonts.bold,fontSize:9,color:colors.secondary,letterSpacing:1,marginBottom:8},deck:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'#F1F5F9',borderRadius:999,paddingHorizontal:12,paddingVertical:9,marginBottom:10},deckOn:{backgroundColor:colors.pink},deckText:{fontFamily:fonts.bold,fontSize:10,color:colors.secondary}});
